NoSQL_Proyecto/NoSQL_Proyecto/Controllers/MetodoPagoController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class MetodoPagoController : Controller
    {
        private readonly MetodoPagoService _metodoPagoService;

        public MetodoPagoController(MetodoPagoService metodoPagoService)
        {
            _metodoPagoService = metodoPagoService;
        }
        public async Task<IActionResult> Metodos()
        {
            var metodos = await _metodoPagoService.GetAsync("Metodo_Pago");

            if (metodos != null)
            {
                return View(metodos);
            }
            else
            {
                return Problem("La lista de metodos es nula.");
            }
        }

        public async Task<IActionResult> EditMetodo(ObjectId id)
        {

            var metodos = await _metodoPagoService.GetAsync("Metodo_Pago", id);

            if (metodos != null)
            {
                return View(metodos);
            }


            return RedirectToAction("Metodos");
        }


        [HttpPost]
        public async Task<IActionResult> EditMetodo(Metodo_Pago model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Actualizar el proveedor en la base de datos
                    await _metodoPagoService.UpdateAsync("Metodo_Pago", model.Id, model);

                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el metodo: " + ex.Message);
                }
            }

            // Obtener nuevamente la lista de proveedores después de la actualización
            var metodos = await _metodoPagoService.GetAsync("Metodo_Pago");

            // Devolver la vista con la lista de proveedores
            return View("Metodos", metodos);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMetodo(ObjectId id)
        {

            await _metodoPagoService.RemoveAsync("Metodo_Pago", id);

            var articulos = await _metodoPagoService.GetAsync("Metodo_Pago");

            return View("Metodos", articulos);
        }


        public IActionResult CreateMetodo()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMetodo(Metodo_Pago metodos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _metodoPagoService.CreateAsync("Metodo_Pago", metodos);
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, "Error al crear el metodo: " + ex.Message);
                }

            }

            var list = await _metodoPagoService.GetAsync("Metodo_Pago");

            // Devolver la vista con la lista de proveedores
            return View("Metodos", list);
        }
    }
}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/MotivoSalidaController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class MotivoSalidaController : Controller
    {
        private readonly MotivoSalidaService _motivoSalidaService;

        public MotivoSalidaController(MotivoSalidaService motivoSalidaService)
        {
            _motivoSalidaService = motivoSalidaService;
        }
        public async Task<IActionResult> Motivos()
        {
            var motivos = await _motivoSalidaService.GetAsync("Motivo_Salida");

            if (motivos != null)
            {
                return View(motivos);
            }
            else
            {
                return Problem("La lista de motivos es nula.");
            }
        }


        public async Task<IActionResult> EditMotivo(ObjectId id)
        {

            var motivos = await _motivoSalidaService.GetAsync("Motivo_Salida", id);

            if (motivos != null)
            {
                return View(motivos);
            }


            return RedirectToAction("Motivos");
        }

        [HttpPost]
        public async Task<IActionResult> EditMotivo(Motivo_Salida model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Actualizar el proveedor en la base de datos
                    await _motivoSalidaService.UpdateAsync("Motivo_Salida", model.Id, model);

                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el motivo: " + ex.Message);
                }
            }

            // Obtener nuevamente la lista de proveedores después de la actualización
            var motivos = await _motivoSalidaService.GetAsync("Motivo_Salida");

            // Devolver la vista con la lista de proveedores
            return View("Motivos", motivos);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteMotivo(ObjectId id)
        {

            await _motivoSalidaService.RemoveAsync("Motivo_Salida", id);

            var metodos = await _motivoSalidaService.GetAsync("Motivo_Salida");

            return View("Motivos", metodos);
        }


        public IActionResult CreateMotivo()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMotivo(Motivo_Salida motivos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _motivoSalidaService.CreateAsync("Motivo_Salida", motivos);
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, "Error al crear el motivo: " + ex.Message);
                }

            }

            var list = await _motivoSalidaService.GetAsync("Motivo_Salida");

            // Devolver la vista con la lista de proveedores
            return View("Motivos", list);
        }
    }
}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/ProveedorController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class ProveedorController : Controller
 
    {
        private readonly ProveedorService _proveedorService;

        public ProveedorController(ProveedorService proveedorService)
        {
            _proveedorService = proveedorService;
        }

        /*
         ESPACIO PARA PROVEEDOR
         
         */
        public async Task<IActionResult> Proveedor()
        {
            var proveedores = await _proveedorService.GetAsync("Proveedor");

            if (proveedores != null)
            {
                return View(proveedores);
            }
            else
            {
                return Problem("La lista de proveedores es nula.");
            }
        }


        public async Task<IActionResult> EditProveedor(ObjectId id)
        {

            var proveedor = await _proveedorService.GetAsync("Proveedor", id);

            if (proveedor != null)
            {
                return View(proveedor);
            }


            return RedirectToAction("Proveedor", "Proveedor");
        }

        [HttpPost]
        public async Task<IActionResult> EditProveedor(Proveedor model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var proveedorActual = await _proveedorService.GetAsync("Proveedor", model.Id);

                    // Actualizar propiedades del proveedor actual
                    proveedorActual.Nombre = string.IsNullOrEmpty(model.Nombre) ? proveedorActual.Nombre : model.Nombre;
                    proveedorActual.Direccion = string.IsNullOrEmpty(model.Direccion) ? proveedorActual.Direccion : model.Direccion;
                    proveedorActual.id_Tipo_Proveedor = model.id_Tipo_Proveedor != null ? model.id_Tipo_Proveedor : proveedorActual.id_Tipo_Proveedor;
                    proveedorActual.Mail = string.IsNullOrEmpty(model.Mail) ? proveedorActual.Mail : model.Mail;
                    proveedorActual.Phone = model.Phone == 0 ? proveedorActual.Phone : model.Phone;
                    proveedorActual.Active = model.Active;

                    // Actualizar el proveedor en la base de datos
                    await _proveedorService.UpdateAsync("Proveedor", proveedorActual.Id, proveedorActual);

                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el proveedor: " + ex.Message);
                }
            }

            // Obtener nuevamente la lista de proveedores después de la actualización
            var proveedores = await _proveedorService.GetAsync("Proveedor");

            // Devolver la vista con la lista de proveedores
            return View("Proveedor", proveedores);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteProveedor(ObjectId id)
        {

            await _proveedorService.RemoveAsync("Proveedor", id);

            var proveedores = await _proveedorService.GetAsync("Proveedor");

            return View("Proveedor", proveedores);
        }


        public IActionResult CreateProveedor()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProveedor(Proveedor proveedor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _proveedorService.CreateAsync("Proveedor", proveedor);
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, "Error al crear el proveedor: " + ex.Message);
                }

            }

            var proveedores = await _proveedorService.GetAsync("Proveedor");

            // Devolver la vista con la lista de proveedores
            return View("Proveedor", proveedores);
        }

        /*
         * FIN DE
         * ESPACIO PARA PROVEEDOR

        */
    }
}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;

namespace NoSQL_Proyecto.Controllers
{
    public class TableController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/TipoArticuloController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class TipoArticuloController : Controller
    {
        private readonly TipoArticulosService _tipoArticuloService;

        public TipoArticuloController(TipoArticulosService tipoArticulosService)
        {
            _tipoArticuloService = tipoArticulosService;
        }

        public async Task<IActionResult> TipoArticulos()
        {
            var tipos = await _tipoArticuloService.GetAsync("Tipo_Articulos");

            if (tipos != null)
            {
                return View(tipos);
            }
            else
            {
                return Problem("La lista de tipos es nula.");
            }
        }

        public async Task<IActionResult> EditTipo(ObjectId id)
        {

            var tipos = await _tipoArticuloService.GetAsync("Tipo_Articulos", id);

            if (tipos != null)
            {
                return View(tipos);
            }


            return RedirectToAction("TipoArticulos");
        }

        [HttpPost]
        public async Task<IActionResult> EditTipo(Tipo_Articulos model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Actualizar el proveedor en la base de datos
                    await _tipoArticuloService.UpdateAsync("Tipo_Articulos", model.Id, model);

                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el tipo: " + ex.Message);
                }
            }

            // Obtener nuevamente la lista de proveedores después de la actualización
            var tipos = await _tipoArticuloService.GetAsync("Tipo_Articulos");

            // Devolver la vista con la lista de proveedores
            return View("TipoArticulos", tipos);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTipo(ObjectId id)
        {

            await _tipoArticuloService.RemoveAsync("Tipo_Articulos", id);

            var tipos = await _tipoArticuloService.GetAsync("Tipo_Articulos");

            return View("TipoArticulos", tipos);
        }


        public IActionResult CreateTipo()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTipo(Tipo_Articulos tipos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _tipoArticuloService.CreateAsync("Tipo_Articulos", tipos);
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, "Error al crear el tipo: " + ex.Message);
                }

            }

            var list = await _tipoArticuloService.GetAsync("Tipo_Articulos");

            // Devolver la vista con la lista de proveedores
            return View("TipoArticulos", list);
        }
    }

}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/TipoUsuarioController.cs
using System.Collections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class TipoUsuarioController : Controller
    {
        private readonly TipoUsuariosService _tipoUsuarioService;

        public TipoUsuarioController(TipoUsuariosService tipoUsuariosService)
        {
            _tipoUsuarioService = tipoUsuariosService;
        }

            public async Task<IActionResult> TipoUsuarios()
            {
                var tipos = await _tipoUsuarioService.GetAsync("Tipo_Usuarios");

                if (tipos != null)
                {
                    return View(tipos);
                }
                else
                {
                    return Problem("La lista de tipos es nula.");
                }
            }

        public async Task<IActionResult> EditTipo(ObjectId id)
        {

            var tipos = await _tipoUsuarioService.GetAsync("Tipo_Usuarios", id);

            if (tipos != null)
            {
                return View(tipos);
            }


            return RedirectToAction("TipoUsuarios");
        }

        [HttpPost]
        public async Task<IActionResult> EditTipo(Tipo_Usuarios model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Actualizar el proveedor en la base de datos
                    await _tipoUsuarioService.UpdateAsync("Tipo_Usuarios", model.Id, model);

                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el tipo: " + ex.Message);
                }
            }

            // Obtener nuevamente la lista de proveedores después de la actualización
            var tipos = await _tipoUsuarioService.GetAsync("Tipo_Usuarios");

            // Devolver la vista con la lista de proveedores
            return View("TipoUsuarios", tipos);
        }



        [HttpPost]
        public async Task<IActionResult> DeleteTipo(ObjectId id)
        {

            await _tipoUsuarioService.RemoveAsync("Tipo_Usuarios", id);

            var tipos = await _tipoUsuarioService.GetAsync("Tipo_Usuarios");

            return View("TipoUsuarios", tipos);
        }

        public IActionResult CreateTipo()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTipo(Tipo_Usuarios tipos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _tipoUsuarioService.CreateAsync("Tipo_Usuarios", tipos);
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError(string.Empty, "Error al crear el tipo: " + ex.Message);
                }

            }

            var list = await _tipoUsuarioService.GetAsync("Tipo_Usuarios");

            // Devolver la vista con la lista de proveedores
            return View("TipoUsuarios", list);
        }

    }
 }

NoSQL_Proyecto/NoSQL_Proyecto/Views/Table/EditProveedor.cshtml
@model NoSQL_Proyecto.Models.Proveedor

<body class="g-sidenav-show bg-gray-100">


    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-md-8">
                <form method="post" asp-action="EditProveedor" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-header pb-0">

                            <div class="d-flex align-items-center">
                                <p class="mb-0">Editar Proveedor</p>
                                <button type="submit" class="btn btn-primary btn-sm ms-auto">Guardar cambios</button>
                            </div>
                        </div>
                        <div class="card-body">
                            <input type="hidden" name="Id" value="@Model.Id">
                            <p class="text-uppercase text-sm">Información de proveedor</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Nombre completo</label>
                                        <input class="form-control" type="text" value="@Model.Nombre" name="Nombre">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Tipo de Proveedor</label>
                                        <input class="form-control" type="text" value="@Model.id_Tipo_Proveedor" name="id_Tipo_Proveedor">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Direccion</label>
                                        <input class="form-control" type="text" value="@Model.Direccion" name="Direccion">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Mail</label>
                                        <input class="form-control" type="email" value="@Model.Mail"  name="Mail">
                                    </div>
                                </div>
                            </div>
                            <hr class="horizontal dark">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Contacto Telefonico</label>
                                        <input class="form-control" type="number" value="@Model.Phone"  name="Phone">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="example-text-input" class="form-control-label">Activo</label>
                                        <input class="form-control" type="text" value="@Model.Active" name="Active">
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <div class="card card-profile" style="display: flex;justify-content: center; align-items: center;">
                  
                    <div class="d-flex justify-content-center" style="margin-top:5px">
                        <form method="post" asp-action="DeleteProveedor" asp-route-id="@Model.Id">
                            <button type="submit" class="btn btn-danger">Eliminar Proveedor</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        handleRegisterResponse('@ViewBag.Success');
    </script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        @if (ViewBag.Success != null && (bool)ViewBag.Success)
        {
            // Mostrar SweetAlert si el registro fue exitoso
            <text>
                Swal.fire({
                    icon: 'success',
                    title: '¡Actualización exitosa!',
                    text: 'Se realizaron los cambios correctamente.',
                    showConfirmButton: false,
                    timer: 2000
                }).then(() => {
                    // Redirigir al usuario a la página de inicio de sesión
                    window.location.href = '@Url.Action("EditProveedor", "Table")';
                });
            </text>
        }
        else if (ViewBag.Success != null && !(bool)ViewBag.Success)
        {
            // Mostrar SweetAlert si el registro falló
            <text>
                Swal.fire({
                    icon: 'error',
                    title: '¡Error al editar!',
                    text: 'Hubo un problema al intentar editar los datos.',
                    showConfirmButton: true
                });
            </text>
        }
    </script>


    <!--   Core JS Files   -->
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>
    <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
                var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/js//argon-dashboard.min.js?v=2.0.4"></script>
</body>

NoSQL_Proyecto/NoSQL_Proyecto/Views/Table/Index.cshtml
@using NoSQL_Proyecto.Services
@using Microsoft.AspNetCore.Http

@inject UsuarioService _usuarioService

@{
    string username = Context.Request.Cookies["Username"];
    bool usuarioTieneRol = _usuarioService.UsuarioTieneRol(username);
}

<body class="g-sidenav-show bg-gray-100">

    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header pb-0">
                            <div class="d-flex align-items-center">
                                <p class="mb-0">Tipos de tablas</p>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                      
                                    <a href="@Url.Action("Articulos","Articulos")" class="btn btn-primary btn-sm ms-auto">Articulos</a>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                    <a href="@Url.Action("Proveedor","Proveedor")" class="btn btn-primary btn-sm ms-auto">Proveedores</a>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                    <a href="@Url.Action("Metodos","MetodoPago")" class="btn btn-primary btn-sm ms-auto">Metodos de pago</a>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                    <a href="@Url.Action("Motivos","MotivoSalida")"  class="btn btn-primary btn-sm ms-auto">Motivos de salida</a>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                    <a href="@Url.Action("TipoArticulos","TipoArticulo")" class="btn btn-primary btn-sm ms-auto">Tipos de articulos</a>
                                    </div>
                                </div>
                                 @if (usuarioTieneRol)
                            {
                                <div class="col-md-3">
                                    <div class="form-group">
                                    <a href="@Url.Action("TipoUsuarios","TipoUsuario")" class="btn btn-primary btn-sm ms-auto"> Tipos de usuarios</a>
                                    </div>
                                </div>
                            }

                            <div class="col-md-3">
                                <div class="form-group">
                                    <a href="@Url.Action("TipoProveedores","TipoProveedor")" class="btn btn-primary btn-sm ms-auto"> Tipos proveedores</a>
                                </div>
                            </div>
       
                            @if (usuarioTieneRol)
                            {
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <a href="@Url.Action("Usuarios","Usuarios")" class="btn btn-primary btn-sm ms-auto">Usuarios</a>
                                    </div>
                                </div>
                            }
                            </div>

                        </div>
                    </div>
      
            </div>

        </div>
    </div>


    <!--   Core JS Files   -->
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>
    <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
                                var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/js//argon-dashboard.min.js?v=2.0.4"></script>

</body>