NoSQL_Proyecto/NoSQL_Proyecto/Controllers/MovimientosController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using NoSQL_Proyecto.Models;
using NoSQL_Proyecto.Services;

namespace NoSQL_Proyecto.Controllers
{
    public class MovimientosController : Controller
    {

        private readonly IngresosService _ingresosService;

        private readonly SalidasService _salidaService;



        public MovimientosController(IngresosService ingresosService, SalidasService salidaService) {

            _ingresosService = ingresosService;

            _salidaService = salidaService;


        }

        /*
            APARTADO DE INGRESOS            

         */

        public IActionResult Ingresos()
        {

            var ingresos = _ingresosService.GetAsync("Ingresos").Result;

            List<IngresosViewModel> ingresoViewModels = new List<IngresosViewModel>();

            foreach (var ingreso in ingresos)
            {
                // Crear una nueva instancia de IngresosViewModel y asignar precio y descripción
                var ingresoViewModel = new IngresosViewModel
                {
                    Cantidad_Ingresada = ingreso.Cantidad_Ingresada,
                    Precio_Compra = ingreso.Precio_Compra
                };
                ingresoViewModels.Add(ingresoViewModel);
            }

            ViewBag.Ingresos = ingresoViewModels;
            return View();
        }

        // POST CREATE
        [HttpPost]
        public async Task<IActionResult> Ingresos(IngresosViewModel model)
        {
            // Verificar si el modelo es válido
            if (ModelState.IsValid)
            {
                // Crear un nuevo salida
                var nuevoIngreso = new Ingresos
                {
                    Fecha_Ingreso = model.Fecha_Ingreso,
                    id_Articulo = ObjectId.Parse("660dc3e881c5953b240d5f51"),
                    Cantidad_Ingresada = model.Cantidad_Ingresada,
                    Precio_Compra = model.Precio_Compra,
                    id_Proveedor = ObjectId.Parse("660dc3e881c5953b240d5f51"),

                    // Asigna otros campos de usuario según sea necesario
                };

                // Intenta crear el salida
                try
                {
                    await _ingresosService.CreateAsync("Ingresos", nuevoIngreso);

                    // Si el salida se crea con éxito, configurar un mensaje de éxito en ViewBag
                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al registrar la salida: " + ex.Message);
                }
            }

            // Si hay errores de validación o si el usuario no se creó correctamente, volver a mostrar el formulario de registro
            return View("Ingresos", model);
        }



        // POST UPDATE





        // POST DELETE







        /*
            APARTADO DE SALIDAS
         
         */



        public IActionResult Salidas()
        {

            var salidas = _salidaService.GetAsync("Salidas").Result;

            List<SalidasViewModel> salidaViewModels = new List<SalidasViewModel>();

            foreach (var salida in salidas)
            {
                // Crear una nueva instancia de IngresosViewModel y asignar precio y descripción
                var salidaViewModel = new SalidasViewModel
                {
                    Fecha_Salida = salida.Fecha_Salida,
                    Cantidad_Vendida = salida.Cantidad_Vendida,
                    Metodo_Pago = salida.Metodo_Pago
                };
                salidaViewModels.Add(salidaViewModel);
            }

            ViewBag.Salidas = salidaViewModels;
            return View();
        }

        // POST CREATE
        [HttpPost]
        public async Task<IActionResult> Salidas(SalidasViewModel model)
        {
            // Verificar si el modelo es válido
            if (ModelState.IsValid)
            {
                // Crear un nuevo salida
                var nuevoSalida = new Salidas
                {
                    Fecha_Salida = model.Fecha_Salida,
                    id_Articulo = ObjectId.Parse("660dc3e881c5953b240d5f51"),
                    Cantidad_Vendida = model.Cantidad_Vendida,
                    Precio_Venta = model.Precio_Venta,
                    Motivo_Salida = ObjectId.Parse("660dc3e881c5953b240d5f51"),
                    Metodo_Pago = ObjectId.Parse("660dc3e881c5953b240d5f51"),

                    // Asigna otros campos de usuario según sea necesario
                };

                // Intenta crear el salida
                try
                {
                    await _salidaService.CreateAsync("Salidas", nuevoSalida);

                    // Si el salida se crea con éxito, configurar un mensaje de éxito en ViewBag
                    ViewBag.Success = true;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error al registrar la salida: " + ex.Message);
                }
            }

            // Si hay errores de validación o si el usuario no se creó correctamente, volver a mostrar el formulario de registro
            return View("Salidas", model);
        }



        // POST UPDATE





        // POST DELETE


    }


}

NoSQL_Proyecto/NoSQL_Proyecto/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;

namespace NoSQL_Proyecto.Controllers
{
    public class TableController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NoSQL_Proyecto/NoSQL_Proyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoSQL_Proyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toggle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NoSQL_Proyecto.styles.css" asp-append-version="true" />
   
    <link rel="apple-touch-icon" sizes="76x76" href="~/apple-icon.png">
<link rel="icon" type="image/png" href="~/favicon.png">
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
<!-- Nucleo Icons -->
<link href="~/css/nucleo-icons.css" rel="stylesheet" />
<link href="~/css/nucleo-svg.css" rel="stylesheet" />
<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="~/css/nucleo-svg.css" rel="stylesheet" />
<!-- CSS Files -->
<link id="pagestyle" href="~/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
<link id="pagestyle" href="~/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
    
</head>
<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">

        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">

                <ul class="navbar-nav  justify-content-end">
                    <li class="nav-item d-flex align-items-center">
                        <a href="@Url.Action("Logout", "Account")" class="nav-link text-white font-weight-bold px-0">
                            <i class="fa fa-user me-sm-1"></i>
                            <span class="d-sm-inline d-none">Cerrar sesión</span>
                        </a>
                    </li>
                    <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                        <a  class="nav-link text-white p-0" id="iconNavbarSidenav">
                            <div class="sidenav-toggler-inner">
                                <i class="sidenav-toggler-line bg-white"></i>
                                <i class="sidenav-toggler-line bg-white"></i>
                                <i class="sidenav-toggler-line bg-white"></i>
                            </div>
                        </a>
                    </li>
                



                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0"  target="_blank">
                <img src="~/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">Inventario</span>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Home")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Index", "Table")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Tables</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Ingresos", "Movimientos")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Ingresos</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Salidas", "Movimientos")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Salidas</span>
                    </a>
                </li>
           
      
                <li class="nav-item mt-3">
                    <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Cuenta</h6>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="@Url.Action("Profile", "Account")">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Perfil</span>
                    </a>
                </li>
                
            </ul>
        </div>

    </aside>


    <div class="container">
        <main class="main-content position-relative border-radius-lg ">
            @RenderBody()
        </main>
        <footer class="footer pt-3  ">
            <div class="container-fluid">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6 mb-lg-0 mb-4">
                        <div class="copyright text-center text-sm text-muted text-lg-start">
                            © <script>
                                  document.write(new Date().getFullYear())
                            </script>,

                            <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Grupo 2</a>
                        </div>
                    </div>

                </div>
            </div>
        </footer>
    </div>
   
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!--   Core JS Files   -->
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/perfect-scrollbar.min.js"></script>
    <script src="~/js/smooth-scrollbar.min.js"></script>
    <script src="~/js/chartjs.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>